"""pass column

Revision ID: 043bee3061d0
Revises: 57515f70bd61
Create Date: 2022-03-01 05:59:21.797266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '043bee3061d0'
down_revision = '57515f70bd61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
